[package]
name = "tracker"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.16", features = ["derive"] }
chrono = "0.4.19"
regex = "1.5.4"
